[book]
authors = ["Doug Bradshaw"]
language = "en"
multilingual = false
src = "src"
title = "An MdBook Tailwindcss Preprocessor Example"

[preprocessor.classy]
command = "../../target/debug/mdbook-tailwindcss"
